/*
  Banco de frases — Biscoito da Sorte
  600 frases × 4 bandas = distribuição por expectativa de biscoitos restantes
  10 temas × 15 frases por banda

  Temas:
  01. presença
  02. gentileza consigo
  03. coragem do cotidiano
  04. descanso sem culpa
  05. autoconhecimento
  06. o corpo e o tempo
  07. alegria pequena
  08. relacionamentos como espelho
  09. memória e identidade
  10. futuro como possibilidade

  Bandas:
  alto  — > 20.000 biscoitos  (tom: expansão, possibilidade, início)
  medio — 10.000–20.000        (tom: profundidade, ritmo, saber-se)
  baixo — 5.000–10.000         (tom: intencionalidade, qualidade, escolha)
  fim   — < 5.000              (tom: presença, completude, legado)
*/

var BANCO = {

/* ════════════════════════════════════════
   ALTO — mais de 20.000 biscoitos
   ════════════════════════════════════════ */
alto: [
/* presença */
'O momento em que você está é o único que existe. Habitá-lo completamente já é suficiente.',
'Respirar fundo não é uma pausa na vida — é a vida acontecendo.',
'Hoje não vai se repetir. Esta versão de você, também não.',
'A atenção é o amor mais puro que você pode oferecer a qualquer coisa.',
'O que está diante de você hoje não é obstáculo — é o caminho.',
'Nenhuma tela mostra o que seus olhos podem ver quando estão realmente abertos.',
'A pressa rouba exatamente aquilo que ela promete encontrar.',
'Qualquer coisa feita com atenção total vira sagrada.',
'Presença não é meditação. É lavar a louça sabendo que está lavando a louça.',
'Seu corpo sabe onde você está. Deixe sua mente chegar também.',
'O mundo muda de cor quando você para de olhar para ele enquanto pensa em outro lugar.',
'Você não precisa fazer mais — precisa estar mais.',
'O cheiro da chuva, o peso do silêncio, o calor de uma mão. Isso é real. O resto é história.',
'Estar aqui, agora, inteiro — isso é tudo que se pede.',
'A vida não acontece nos grandes momentos. Ela acontece nos intervalos entre eles.',

/* gentileza consigo */
'Você falaria assim com alguém que ama? Então não fale assim com você.',
'Exigir mais de si não é virtude se vier acompanhado de desprezo.',
'A voz que te critica mais forte não é a mais sábia — é apenas a mais antiga.',
'Você não precisa se tornar alguém melhor para merecer cuidado. Você já merece.',
'Seus erros não definem quem você é. Definem o que você aprendeu.',
'Seja paciente com seu progresso. Raízes levam mais tempo que galhos.',
'O que você vê como falha, outros veem como humanidade.',
'Se você esperasse perfeição das flores, nunca apreciaria nenhuma.',
'Cuide de si como cuidaria de alguém que você ama profundamente.',
'Você sobreviveu a tudo que tentou te derrubar. Isso merece respeito.',
'Seu ritmo não é lento. É o seu ritmo.',
'A autocompaixão não é conformismo — é o solo onde o crescimento real acontece.',
'Você não é uma versão inacabada de alguém melhor. É uma versão completa de você mesmo.',
'Gentileza consigo não é fraqueza — é a base de qualquer força duradoura.',
'Tratar-se bem não é egoísmo. É o pré-requisito de tudo.',

/* coragem do cotidiano */
'Acordar e tentar de novo depois de ontem ter sido difícil — isso é coragem.',
'Dizer não quando você quer dizer não é um ato revolucionário.',
'Mostrar quem você é sem pedir desculpa por isso exige mais bravura que qualquer batalha.',
'Recomeçar não é fraqueza. É a habilidade mais rara que existe.',
'Pedir ajuda quando precisa é a coisa mais corajosa que alguém pode fazer.',
'A coragem não faz o medo desaparecer. Ela age mesmo com ele presente.',
'Mudar de ideia quando você aprende algo novo não é inconsistência — é inteligência.',
'Dizer "não sei" com tranquilidade é uma das formas mais altas de saber.',
'Escolher o que é certo para você, mesmo sem aprovação, é um dos maiores presentes que pode se dar.',
'Não é preciso ser invulnerável para ser forte. Às vezes é o contrário.',
'A coragem de ser ordinário num mundo que exige grandiosidade é profundamente subversiva.',
'Você não precisa de certeza para dar o próximo passo. Só precisa do próximo passo.',
'Admitir que está cansado é o primeiro ato de quem vai continuar.',
'Cada dia em que você se levanta e tenta é um ato de fé em si mesmo.',
'Tentar e falhar ainda conta. A tentativa é o que separa quem vive de quem espera.',

/* descanso sem culpa */
'Parar não é perder tempo. É o tempo que permite todo o resto.',
'Você não é uma máquina. Nem deveria querer ser.',
'O descanso não precisa ser merecido. Ele é necessário.',
'Fazer nada de forma intencional é um dos atos mais sofisticados que existem.',
'Seu valor não está na sua produtividade. Nunca esteve.',
'O sono que você protege é tão importante quanto o trabalho que você entrega.',
'Cansaço não resolvido não vai embora sozinho. Ele acumula juros.',
'Descansar é um ato de respeito pelo que vem depois.',
'Você não precisa justificar uma tarde de nada a ninguém.',
'Silêncio não é vazio. É o lugar onde você se encontra.',
'Não existe descanso errado se ele te renova.',
'Você não precisa estar em movimento para estar evoluindo.',
'O prazer sem propósito tem propósito: ele te lembra que você está vivo.',
'Desacelerar é uma habilidade. Poucas pessoas a cultivam.',
'A preguiça que sente culpa não é preguiça — é seu corpo pedindo socorro.',

/* autoconhecimento */
'Conhecer seus limites não é se diminuir — é se respeitar.',
'Você não precisa explicar quem você é para quem não está disposto a entender.',
'Saber o que te faz bem é tão importante quanto saber o que te faz mal.',
'Você não precisa entender tudo sobre si mesmo para se aceitar completamente.',
'Seus padrões repetidos são seus professores mais honestos.',
'A versão de você que você esconde com vergonha geralmente é a mais interessante.',
'Autoconhecimento não é uma lista de defeitos. É um mapa de possibilidades.',
'O que você escolhe notar sobre si mesmo molda quem você se torna.',
'Ninguém te conhece completamente — nem você. E tudo bem.',
'Suas reações são dados sobre você. Não são você.',
'Reconhecer o que você sente sem precisar justificar é maturidade emocional pura.',
'Quanto mais você se conhece, menos precisa da aprovação de quem não te conhece.',
'Você tem camadas. Algumas você ainda está descobrindo. Isso é bonito.',
'A parte de você que observa seus próprios pensamentos é mais livre do que pensa.',
'O que te incomoda nos outros frequentemente revela algo sobre você. Vale a pena olhar.',

/* o corpo e o tempo */
'Seu corpo carrega tudo que você já viveu. Trate-o como o arquivo precioso que é.',
'O corpo não mente. Aprenda a língua que ele fala.',
'Você vai ser mais jovem hoje do que amanhã. Use esse corpo agora.',
'Dor não é fraqueza saindo. É informação chegando.',
'O tempo que você passa no seu próprio corpo é o mais honesto de todos.',
'Mover-se é uma forma de pensar que muitos esqueceram.',
'Seu corpo tem memória. Cuide do que você grava nele.',
'Você não precisa ter o corpo perfeito para habitá-lo plenamente.',
'O cansaço físico honesto é um dos melhores soníferos que existem.',
'Respiração é a única função automática que você pode controlar. Isso diz muito.',
'O que você come, como dorme, como se move — tudo é uma conversa com quem você será.',
'Seu corpo hoje é diferente do de ontem. Conheça-o de novo.',
'Prazer físico não precisa de justificativa. É parte do pacote de estar vivo.',
'O tempo no corpo é diferente do tempo no relógio. Respeite os dois.',
'Envelhecer não é perder algo. É ganhar a versão de você que sobreviveu a tudo.',

/* alegria pequena */
'A alegria não precisa ser grande para ser real.',
'O café da manhã em silêncio é uma das experiências mais subestimadas da existência.',
'Rir de algo bobo com alguém que você gosta é uma das formas mais puras de conexão.',
'Coisas pequenas não são menos importantes. São mais frequentes — e a frequência é o que faz a vida.',
'A felicidade raramente chega de uma vez. Ela aparece em flashes. Aprenda a vê-los.',
'O que te deu alegria hoje? Se você não sabe, procure mais devagar.',
'Você tem permissão para desfrutar de coisas pequenas sem esperar pelas grandes.',
'A leveza é uma conquista, não uma superficialidade.',
'Uma tarde sem compromisso é um luxo que não precisa de dinheiro.',
'O barulho da chuva, a luz de fim de tarde, o cheiro de livro velho — isso não é pouco.',
'Alegria não gerenciada é a melhor versão dela.',
'Humor é uma forma de inteligência emocional. Ria mais.',
'O prazer de não ter pressa é subestimado por quem nunca o experimentou de propósito.',
'Existir e sentir que vale a pena existir é o suficiente para um bom dia.',
'Há dignidade em apreciar o simples sem precisar chamá-lo de suficiente.',

/* relacionamentos como espelho */
'Quem você escolhe ter por perto revela o que você acredita merecer.',
'As pessoas que ficam quando é difícil são as que importam quando é fácil.',
'Você não precisa ser amado por todos. Precisa ser amado de verdade por alguns.',
'O que você não consegue dar a si mesmo, não consegue receber de ninguém.',
'Quem te faz sentir pequeno não cabe no seu tamanho real.',
'Amar alguém não é se perder nele. É continuar sendo você junto com ele.',
'A qualidade das suas conversas define muito da qualidade da sua vida.',
'Você não precisa de muitos — precisa de verdadeiros.',
'Fronteiras não afastam quem te ama. Elas mostram quem realmente te ama.',
'A vulnerabilidade não é o oposto da força — é o que permite conexão real.',
'Você não deve nada a quem nunca se dispôs a te ver de verdade.',
'Amor que exige que você se diminua não é amor — é controle com outro nome.',
'As pessoas que te fazem sentir mais você mesmo são as mais preciosas.',
'Relacionamentos saudáveis não eliminam a solidão. Eles a tornam suportável.',
'Às vezes a pessoa que você mais precisa entender é você mesmo.',

/* memória e identidade */
'Você não é a soma dos seus piores momentos.',
'O passado não define quem você é. Ele explica de onde você veio.',
'Guardar boas memórias não é nostalgia — é nutrição.',
'Você já foi alguém que não sabia o que sabe hoje. Tenha compaixão por essa pessoa.',
'Identidade não é algo que você encontra. É algo que você constrói, escolha a escolha.',
'As memórias que você revisita com carinho moldam quem você está se tornando.',
'Você é uma continuidade, não um reinício. Tudo que você viveu está em você.',
'Não existe versão sua que foi desperdiçada. Cada uma foi necessária.',
'Sua forma de ser no mundo é única. Não existe backup.',
'O que você lembra de si mesmo com orgulho é um mapa do que você realmente valoriza.',
'Você pode reescrever a narrativa do seu passado sem falsificar os fatos.',
'A criança que você foi ainda está em você. Cuide dela às vezes.',
'Quem você era não limita quem você pode ser — a menos que você decida que sim.',
'Cada fase sua teve sabedoria própria. Não despreze nenhuma.',
'Sua história tem partes que você ainda está entendendo. Dê tempo.',

/* futuro como possibilidade */
'O futuro não é uma ameaça a ser gerenciada. É um espaço a ser preenchido.',
'Você não precisa saber como vai chegar para saber onde quer estar.',
'O melhor que vai acontecer na sua vida ainda não aconteceu.',
'Possibilidade não exige certeza — exige abertura.',
'Você vai surpreender a si mesmo ainda muitas vezes. Mantenha espaço para isso.',
'Sonhar grande não é ingenuidade. É uma das formas mais sérias de se levar a sério.',
'Você não precisa ter tudo resolvido para começar o que importa.',
'O que você planta hoje em você mesmo é o que vai colher amanhã.',
'Ansiedade sobre o futuro é amor mal direcionado. Redirecione para o presente.',
'Você tem mais opções do que pensa. Sempre teve.',
'O próximo capítulo não precisa se parecer com nenhum dos anteriores.',
'Abrir-se para o que você ainda não imaginou é o maior ato de confiança em si mesmo.',
'Você não sabe o que está por vir. Isso, por si só, é uma boa notícia.',
'Planejar é útil. Controlar é ilusão. Saiba a diferença.',
'O futuro não espera por você — mas ele tem lugar para você quando você aparecer.'
],

/* ════════════════════════════════════════
   MEDIO — 10.000 a 20.000 biscoitos
   ════════════════════════════════════════ */
medio: [
/* presença */
'Você já sabe que os melhores momentos não avisam que estão chegando.',
'Aqui é onde tudo acontece. Aqui — não lá, não antes, não depois.',
'A vida que você está vivendo agora vai se tornar a história que você vai contar.',
'Depois de tudo que já passou, você sabe: o presente é o único lugar seguro.',
'Prestar atenção é a única forma de não perder o que está acontecendo.',
'Nada do que você está pensando no passado ou no futuro é tão real quanto este momento.',
'O silêncio entre as coisas é onde a vida respira.',
'Estar completamente em algum lugar é mais raro e mais valioso do que qualquer conquista.',
'O que você notaria se parasse de pensar em outra coisa por cinco minutos?',
'Você aprendeu que a presença não é sobre ter paz — é sobre estar, mesmo sem ela.',
'Cada segundo que você está realmente aqui é subtraído do tempo que você passa perdido.',
'Você já viveu o suficiente para saber que o momento vai embora. Então fique nele.',
'Atenção plena não é uma técnica. É uma escolha que você renova todo instante.',
'O que está bem na sua vida agora? Nomear isso também é uma prática.',
'Presença é o maior presente que você pode dar — a qualquer pessoa, incluindo você.',

/* gentileza consigo */
'Você já carregou peso demais por tempo demais. Pode pousar um pouco.',
'A versão de você que errou muito já contribuiu muito. Honre-a.',
'Você aprendeu — às vezes na dor — que se criticar demais não te tornou melhor. Tornou-te mais exausto.',
'Tratar-se bem ficou mais fácil com o tempo, ou mais difícil? De qualquer forma, vale continuar.',
'Você merece a mesma paciência que ofereça às pessoas que ama.',
'A gentileza consigo não é algo que se conquista de uma vez. É um retorno constante.',
'Você já passou por fases que exigiram mais do que você tinha. O que ficou é força.',
'Menos autocrítica. Mais observação. Há uma diferença enorme entre os dois.',
'Você não precisa se sentir bem consigo mesmo o tempo todo. Precisa continuar se escolhendo.',
'O que você faria diferente não define o que você fará agora.',
'Compaixão não tem prazo de validade. A de hoje é tão válida quanto a de sempre.',
'Você se cobrou muito. Em algum momento, cobrar menos vai ser a coisa mais produtiva.',
'Há uma diferença entre melhorar e se punir. Você já sabe isso — aplique mais.',
'Cuide de si com a mesma seriedade com que cuida das pessoas que dependem de você.',
'Você não precisa justificar sua necessidade de gentileza para ninguém — nem para si mesmo.',

/* coragem do cotidiano */
'Você já provou que consegue atravessar o que parecia impossível. Isso não muda.',
'A coragem que você exerceu silenciosamente ninguém viu — mas ela foi real.',
'Continuar quando tudo pede para parar é uma forma de bravura que poucos reconhecem.',
'Você não precisa mais provar coragem para os outros. A prova que importa é para você mesmo.',
'A escolha de ser honesto quando mentir seria mais fácil — isso é coragem do cotidiano.',
'Fazer o que é certo quando ninguém está olhando é a versão mais pura da integridade.',
'Você aprendeu que recomeços não são derrota. São estratégia.',
'A coragem de dizer "mudei de ideia" após anos acreditando em algo exige mais que qualquer aventura.',
'Continuar crescendo quando crescer dói é uma das formas mais silenciosas de bravura.',
'Você já teve medo e fez assim mesmo. Vai fazer de novo.',
'Fronteiras que você estabeleceu com dificuldade foram atos de coragem — não egoísmo.',
'Ser vulnerável com as pessoas certas exigiu mais de você do que qualquer outra coisa.',
'Você sabe agora que o arrependimento de não tentar é mais pesado que o de ter tentado.',
'A persistência silenciosa de quem cuida de si mesmo dia após dia é coragem em forma de rotina.',
'Mostrar sua fragilidade a quem merece vê-la é um dos atos mais corajosos que existem.',

/* descanso sem culpa */
'Você já aprendeu — ou está aprendendo — que descanso não é recompensa. É parte do processo.',
'O seu sistema precisa de pausa para integrar o que viveu. Não é preguiça. É fisiologia.',
'Você pode parar agora. O que é importante vai continuar sendo importante depois.',
'A exaustão que você ignorou por anos agora pede contas. Ouça antes que ela grite.',
'Há um tipo de descanso que só a quietude oferece. Você sabe qual é.',
'Você não deve produtividade ininterrupta a ninguém — nem ao mercado, nem a si mesmo.',
'O prazer de uma tarde vaga é legítimo. Você não precisa mais justificá-lo.',
'Parar de vez em quando não interrompe sua história — faz parte dela.',
'O que você perde ao descansar é sempre menor do que o que ganha.',
'Você aprendeu que ignorar o cansaço funciona por um tempo. Depois ele cobra com juros.',
'Há sabedoria em saber quando parar. Não apenas quando começar.',
'Descanso profundo é diferente de escapismo. Você já sabe a diferença.',
'Nada que você precise descansar para fazer deixa de valer a pena por isso.',
'Quanto mais você se cuida, mais presente você está para o que importa.',
'Você não é mais eficiente quando está esgotado. Isso é um fato, não uma desculpa.',

/* autoconhecimento */
'Você já viveu o suficiente para saber algumas coisas sobre si mesmo com certeza.',
'Os padrões que você repetiu por anos agora você consegue nomear. Nomear é o primeiro passo.',
'Você sabe o que te faz bem. A questão agora é se permitir isso com mais frequência.',
'Autoconhecimento acumulado não é arrogância — é orientação.',
'Você já foi a pessoa que não entendia por que agia assim. Agora entende um pouco mais.',
'Seus valores ficaram mais claros com o tempo. Confie neles.',
'O que você descobriu sobre si mesmo nos momentos difíceis é o que você realmente é.',
'Você aprendeu que algumas perguntas sobre si mesmo não têm resposta — e está bem assim.',
'A autoconsciência que você cultivou ao longo dos anos é um dos seus bens mais valiosos.',
'Você já sabe que se conhecer não é se fixar — é continuar descobrindo.',
'O que te movia há dez anos ainda te move? Se não, o que mudou? Isso é autoconhecimento.',
'Você é capaz de observar seus próprios pensamentos sem se identificar completamente com eles.',
'Reconhecer seu próprio limite antes de ultrapassá-lo é uma habilidade que levou tempo para aprender.',
'Você aprendeu que ser autêntico tem um custo — e que o custo de não ser é maior.',
'Suas contradições não são defeitos. São a prova de que você é complexo o suficiente para ser real.',

/* o corpo e o tempo */
'Seu corpo já carregou muita coisa. Trate-o com a gratidão que merece.',
'Você está no meio da vida — o corpo que você tem agora vai com você até o fim. Invista nele.',
'O que seu corpo pede com mais frequência e você ignora com mais frequência?',
'Cuidar do corpo não é vaidade — é respeito pela única casa que você tem.',
'Você aprendeu que o corpo avisa antes de adoecer. Aprenda a ouvi-lo antes.',
'O tempo que você gasta cuidando de si fisicamente não é subtraído da vida — é adicionado.',
'Há uma inteligência no seu corpo que sua mente não alcança. Preste atenção a ela.',
'Cada ano que passa, o corpo pede mais atenção e menos descaso. É justo.',
'Você já sentiu como um corpo descansado e bem cuidado pensa diferente. Busque isso.',
'O movimento que você escolhe não precisa ser performance. Pode ser apenas conversa com o corpo.',
'Seu corpo guarda muito do que sua mente preferiu esquecer. Seja gentil com ele.',
'Envelhecer com saúde não é sorte apenas — é a soma das escolhas que você faz hoje.',
'O prazer que seu corpo sente é tão legítimo quanto qualquer realização intelectual.',
'Você está no tempo certo para cuidar melhor do que te leva adiante.',
'O corpo que você tem hoje é o resultado de tudo que você viveu. É feito de história.',

/* alegria pequena */
'Você já sabe que os momentos mais memoráveis raramente foram os planejados.',
'O que você faz simplesmente porque gosta, sem propósito além disso, é essencial.',
'Pequenas alegrias acumuladas formam uma vida que vale a pena — não os grandes eventos.',
'Você já viveu o suficiente para saber que a leveza precisa ser cultivada, não esperada.',
'Há coisas que te fazem bem que você ainda não se dá permissão de fazer com frequência.',
'Alegria não é o destino — é o que acontece quando você deixa de adiar o que te faz bem.',
'O que faz seus olhos brilharem sem explicação? Faça mais isso.',
'Você sabe que alegria não é ausência de problemas. É presença de algo que vale.',
'Rir com facilidade é um superpoder. Preserve-o.',
'Uma boa risada com alguém que você ama ainda é uma das melhores experiências disponíveis.',
'Você não precisou de muito, nas melhores tardes da sua vida. Lembre-se disso.',
'Há prazer em coisas simples que você ainda não redescobriu. Vá lá.',
'A alegria que você compartilha multiplica. A que você guarda apenas para si também tem valor.',
'Desfrutar sem culpa ainda está em construção para você? Trabalhe nisso.',
'O que te fez sorrir hoje sem motivo grande é exatamente o tipo de coisa que importa.',

/* relacionamentos como espelho */
'As relações que você mantém até aqui revelam o que você aprendeu sobre si mesmo.',
'Quem você escolheu manter por perto diz muito sobre o que você valoriza agora.',
'Você já sabe que qualidade de relação não se mede por quantidade de tempo — mas de presença.',
'Os relacionamentos que te fizeram crescer foram os que também te desafiaram. Não é coincidência.',
'Você aprendeu que amor que não respeita seus limites não é amor — e isso mudou algo em você.',
'Quem está ao seu lado quando você não está bem é quem importa.',
'Você já entende que pessoas que te fazem ser mais você mesmo são raras e valem muito.',
'A forma como você trata as pessoas que mais ama quando está exausto diz muito sobre você.',
'Relacionamentos honestos exigem coragem que muita gente não tem. Você tem?',
'Você aprendeu que solidão dentro de uma relação é a mais pesada das solidões.',
'Quem você deixou ir que precisava ir? Isso também foi amor.',
'As conversas mais importantes da sua vida — você já as teve? Algumas ainda estão por vir.',
'Você sabe agora que presença real em uma relação é mais rara que fidelidade.',
'Quanto de você você mostra para as pessoas mais próximas? O suficiente?',
'Amar bem é uma habilidade. Você está melhorando nela.',

/* memória e identidade */
'Você já viveu o suficiente para ter histórias que te definem. Cuide da narrativa.',
'A pessoa que você era há dez anos reconheceria quem você é agora com orgulho?',
'Sua identidade está em movimento constante — e isso não é instabilidade, é crescimento.',
'Você carrega experiências que poucas pessoas têm. Elas são parte do que te torna raro.',
'O que você escolheu lembrar sobre si mesmo é parte de quem você decidiu ser.',
'Há uma continuidade entre todas as versões de você. Ela se chama caráter.',
'Você aprendeu coisas sobre si mesmo nas perdas que as vitórias não poderiam ensinar.',
'Sua história tem capítulos que você não escolheu — mas a narrativa, sim, você escolhe.',
'As versões de você que você tem vergonha merecem compreensão, não apagamento.',
'Quem você é hoje não é quem você sempre foi — e é exatamente quem você deveria ser agora.',
'A memória que você cultiva de si mesmo tem poder sobre quem você continuará sendo.',
'Você já passou por transformações que outros nem perceberam. Você percebeu.',
'A identidade que você construiu tem partes fortes que você ainda subestima.',
'Reconhecer sua própria evolução não é arrogância — é honestidade.',
'Você tem uma história única. Vale a pena conhecê-la com mais profundidade.',

/* futuro como possibilidade */
'Você ainda vai se surpreender com o que é capaz de fazer.',
'O que você ainda quer viver que ainda não viveu? Essa lista não deve encolher.',
'Você aprendeu que planos mudam — mas intenções bem colocadas costumam chegar.',
'Ainda há versões de você que não foram exploradas. Isso é uma boa notícia.',
'O futuro que você quer não exige que você seja outra pessoa — exige que você seja mais você.',
'Você já fez apostas em si mesmo que valeram a pena. Faça mais.',
'O que você vai começar agora que vai agradecer em dez anos?',
'Você não está tarde para nada que ainda importa para você.',
'A vida na segunda metade pode ser mais intensa do que a primeira. Depende de você.',
'O que você ainda quer aprender? Essa resposta diz muito sobre quem você está se tornando.',
'Você tem experiência suficiente para fazer escolhas melhores do que antes. Use isso.',
'O futuro não precisa ser uma versão melhorada do passado. Pode ser algo completamente diferente.',
'Há coisas que só quem chegou até aqui pode fazer. Pense nisso.',
'O que você vai fazer com o que ainda tem pela frente?',
'Cada escolha que você faz agora é uma mensagem para a versão futura de você mesmo.'
],

/* ════════════════════════════════════════
   BAIXO — 5.000 a 10.000 biscoitos
   ════════════════════════════════════════ */
baixo: [
/* presença */
'Cada momento em que você está realmente aqui se torna mais valioso. Esteja aqui.',
'A presença agora não é uma técnica — é a única coisa que você pode oferecer de verdade.',
'Você já viu tempo o suficiente para saber que ele não volta. Então fique aqui.',
'O que está acontecendo ao seu redor agora mesmo? Veja com os olhos, não com a memória.',
'Minutos vividos com presença valem mais do que horas vividas no piloto automático.',
'Aqui é onde tudo o que você tem está. Não existe outro lugar mais real.',
'A qualidade dos seus dias está diretamente ligada à qualidade da sua atenção.',
'Você ainda vai ter muitos momentos. Mas este momento não vai se repetir.',
'Não é o que você faz que define o dia — é com quanto de você você fez.',
'Parar para sentir o que está acontecendo agora é um ato de inteligência.',
'O tempo que você já viveu ensinou você a estar aqui. Use esse aprendizado.',
'Presença inteira num único momento vale mais do que presença parcial em dez.',
'O que você está sentindo agora — não o que deveria sentir, mas o que sente — é o ponto de partida.',
'Você aprendeu que a vida não está alhures. Está exatamente onde você está.',
'Este momento, vivido inteiramente, já é suficiente.',

/* gentileza consigo */
'Você merece a mesma gentileza que dispensou às pessoas que ama ao longo da vida.',
'A dureza que você se impôs cumpriu seu papel. Agora pode ser substituída por algo mais inteligente.',
'Você carregou muito. Pode pousar algumas coisas que já não servem.',
'Tratar-se bem agora não é tarde. É exatamente a hora certa.',
'A voz crítica interna que te acompanhou até aqui não precisa mais guiar — pode descansar.',
'Você sobreviveu com menos gentileza consigo do que merecia. Isso muda agora.',
'O cuidado que você dedica a si mesmo agora é proporcional ao que vai conseguir dar aos outros.',
'Suas imperfeições são parte do que te torna humano e, portanto, amável.',
'Você não precisa ter sido perfeito para merecer paz agora.',
'O quanto você se cuida é um ensinamento silencioso para quem está ao seu redor.',
'Aceitar-se não é desistir de crescer. É parar de crescer em guerra consigo mesmo.',
'Gentileza consigo não tem pré-requisito. Você não precisa ganhar esse direito.',
'O que você diria para si mesmo de vinte anos atrás? Diga isso para si mesmo agora.',
'Você aprendeu muito sobre os outros. Já sabe o suficiente sobre você para ser seu próprio aliado.',
'Ser gentil consigo é a fundação, não o teto.',

/* coragem do cotidiano */
'A coragem que você exerceu ao longo da vida não desaparece — ela se acumula.',
'Continuar sendo honesto consigo mesmo quando é desconfortável é a maior coragem.',
'Você ainda vai precisar de bravura. Felizmente, você já sabe de onde ela vem.',
'A coragem de dizer "esse não é mais o meu caminho" é uma das mais maduras.',
'Mudar quando mudar é assustador continua sendo ato de bravura — em qualquer fase.',
'Você já enfrentou coisas que pareciam impossíveis. Isso não foi sorte — foi você.',
'A coragem de se mostrar vulnerável quando você poderia se proteger é o que cria conexão real.',
'Fazer o que é certo quando é inconveniente é exatamente o tipo de coragem que conta.',
'Você não precisa de circunstâncias heroicas para ser corajoso. O cotidiano é suficiente.',
'Pedir perdão quando precisa. Dar perdão quando pode. Isso também é coragem.',
'A bravura de continuar cuidando de si mesmo mesmo quando ninguém vê é das mais puras.',
'Você ainda tem decisões difíceis pela frente. Você tem o que precisa para tomá-las.',
'Recusar o que não te faz bem, mesmo que seja confortável, exige coragem constante.',
'O que você ainda precisa de coragem para fazer? A resposta importa.',
'A coragem acumulada ao longo dos anos virou sabedoria. Use-a.',

/* descanso sem culpa */
'Você merece descanso não porque está exausto, mas porque é humano.',
'A paz que o descanso oferece não é passividade — é recarga para o que ainda vem.',
'Você já provou tudo que tinha que provar. Agora pode descansar um pouco mais.',
'Descanso nesta fase da vida é tão estratégico quanto qualquer trabalho.',
'O que você ainda está carregando que poderia pousar? Agora é um bom momento.',
'Silêncio não é vazio — é onde você processa tudo que viveu.',
'Você tem permissão para diminuir o ritmo sem se sentir menor por isso.',
'Descanso intencional agora é um investimento no que você ainda vai viver.',
'Você não precisa estar ocupado para ser relevante.',
'O prazer de simplesmente existir sem agenda é algo que você merece experimentar mais.',
'Não há conquista que justifique negligenciar o descanso que você precisa.',
'Você aprendeu que cansaço crônico embota tudo — percepção, julgamento, alegria.',
'Um dia inteiro sem obrigações não é desperdício. É nutrição.',
'O ritmo que faz sentido para você agora não precisa ser o ritmo de antes.',
'Parar é, às vezes, a coisa mais produtiva que você pode fazer.',

/* autoconhecimento */
'Você passou anos se conhecendo. O que você aprendeu sobre si mesmo é valioso.',
'Confiar em si mesmo mais do que você confia é uma escolha disponível a você.',
'Você sabe o que te faz bem. Você sabe o que te faz mal. Aja com esse conhecimento.',
'As partes de você que você ainda está descobrindo são as mais interessantes.',
'Você tem mais sabedoria sobre si mesmo do que muitas vezes se permite reconhecer.',
'O autoconhecimento que você acumulou é uma bússola — use-a.',
'Você aprendeu que algumas perguntas sobre você mesmo levam a vida inteira para responder. E tudo bem.',
'Sua intuição sobre si mesmo ficou mais afinada com o tempo. Confie nela mais.',
'Você já conhece suas tendências o suficiente para não se surpreender com elas — apenas observá-las.',
'O que ainda te surprende em você mesmo? Essa pergunta tem respostas valiosas.',
'Você sabe quando precisa de espaço, quando precisa de conexão, quando precisa de silêncio. Honre isso.',
'Autoconhecimento real é humilde — não presunçoso. Você está no caminho certo.',
'As partes de você que você ainda não entende completamente merecem curiosidade, não julgamento.',
'Você viveu o suficiente para saber que se conhecer é um processo sem fim. Isso é libertador.',
'O que você descobriu sobre seus limites foi, muitas vezes, um presente disfarçado.',

/* o corpo e o tempo */
'Seu corpo chegou até aqui com você. Isso merece gratidão e cuidado.',
'O corpo que você tem agora é o resultado de tudo que você viveu — honre-o.',
'Cuidar do corpo agora é cuidar de quem você ainda vai ser.',
'Você aprendeu que o corpo cobra o que você ignorou. Ouça antes da cobrança.',
'O movimento que faz seu corpo bem também faz sua mente bem — sem exceção.',
'Há prazer físico que só quem conhece o próprio corpo consegue sentir. Você conhece o seu?',
'Seu corpo hoje é diferente do que era — e tem uma beleza própria que merece ser reconhecida.',
'Descanso físico não é opcional nesta fase. É fundamental.',
'O tempo que você dedica ao seu bem-estar físico é multiplicado em qualidade de vida.',
'Você aprendeu que ignorar o corpo tem um preço. Agora pode pagar menos esse preço.',
'Seu corpo carrega a história de tudo que você superou. É mais forte do que parece.',
'A relação que você tem com seu corpo reflete a relação que você tem consigo mesmo.',
'Mover-se, respirar com atenção, dormir bem — são os atos mais radicais de autocuidado.',
'O que seu corpo pede com mais frequência é o que merece sua atenção mais consistente.',
'Envelhecer com consciência é diferente de envelhecer com resistência. Você escolhe.',

/* alegria pequena */
'O que te dá alegria pequena e frequente é mais importante do que qualquer realização grande.',
'Você sabe agora que os melhores momentos foram os mais simples.',
'Permitir-se alegria sem motivo grandioso é uma das habilidades mais valiosas.',
'O que você faz simplesmente porque gosta, sem mais, é parte essencial de quem você é.',
'A leveza que você cultiva agora é um presente para todos ao seu redor.',
'Você merece momentos de alegria pura sem precisar justificá-los.',
'Há prazeres simples que você ainda não redescobriu. Eles estão esperando.',
'Uma boa risada com quem você ama ainda é um dos melhores remédios conhecidos.',
'Alegria não precisa de ocasião especial. Ela cabe em qualquer terça-feira.',
'O que faz você esquecer o tempo quando está fazendo? Faça isso mais.',
'Você aprendeu que grandes eventos não garantem alegria. Momentos pequenos sim.',
'Beleza está em lugares que você passou sem notar. Desacelere para vê-la.',
'O que você aprecia hoje que antes ignorava? Isso é maturidade emocional.',
'Sorrir com facilidade ainda é um superpoder. Cuide dele.',
'A alegria que você irradia quando está bem é um presente que você dá sem perceber.',

/* relacionamentos como espelho */
'As relações que você manteve ao longo dos anos revelam o melhor de você.',
'Quem ainda está ao seu lado depois de tudo diz algo muito claro sobre o valor do que vocês construíram.',
'Você aprendeu que amor duradouro não é ausência de conflito — é compromisso com o outro apesar dele.',
'As relações que te machucaram ensinaram tanto quanto as que te curaram.',
'Quem você ainda quer perto nos próximos anos? Invista nessas pessoas agora.',
'Você sabe que presença real numa relação é mais rara do que lealdade.',
'As pessoas que te conhecem de verdade são um tesouro. Cuide delas.',
'Amor que cresceu com o tempo tem uma profundidade que o amor novo não tem. Honre isso.',
'Você aprendeu que se dar ao outro sem se perder é possível — e é o único tipo de amor que sustenta.',
'Quem você precisou perdoar para seguir em frente? Esse perdão também foi para você.',
'As conversas mais importantes que você ainda pode ter estão esperando por você.',
'Você sabe agora que estar presente para alguém é o maior presente que pode dar.',
'Relações que te fazem ser mais você mesmo são raras. Cuide delas como cuida das coisas preciosas.',
'O quanto você permite ser visto pelas pessoas que ama define a profundidade do que vocês compartilham.',
'Amar bem é uma das formas mais sofisticadas de se conhecer.',

/* memória e identidade */
'Você chegou até aqui. Isso por si só é uma história de persistência.',
'A pessoa que você é hoje foi construída por cada escolha que você fez — incluindo as difíceis.',
'Você tem uma identidade que foi testada e que resistiu. Isso é raro.',
'As memórias que você carrega com orgulho dizem mais sobre você do que seus títulos.',
'Sua história é singular. Não existe outra igual. Isso tem valor incalculável.',
'Você superou versões de si mesmo que precisavam ser superadas. Isso é evolução real.',
'O que permaneceu em você depois de tudo que passou é o núcleo do que você é.',
'Você tem o direito de se orgulhar do caminho que percorreu, mesmo com os desvios.',
'A pessoa que você se tornou não foi acidente. Foi a soma de cada decisão de continuar.',
'Você viveu coisas que moldaram quem você é de formas que nem sempre você percebe.',
'Sua identidade não precisa ser explicada. Ela se mostra em como você age.',
'Há capítulos da sua história que só agora você consegue ver com clareza e compaixão.',
'O que você preservou de si mesmo ao longo de tudo é o que mais importa.',
'Você não é o que aconteceu com você. É o que você fez com o que aconteceu.',
'Sua história ainda não acabou — e as melhores histórias muitas vezes têm reviravolta no final.',

/* futuro como possibilidade */
'O que você ainda quer viver é tão válido quanto o que você já viveu.',
'Você tem experiência suficiente para fazer as próximas escolhas com mais sabedoria.',
'O futuro que você imagina para si mesmo ainda pode ser construído. Agora.',
'Há coisas que só quem chegou até aqui consegue fazer. Você está nesse lugar.',
'Você ainda vai se surpreender com o que é capaz de sentir, criar e oferecer.',
'O que você ainda quer aprender? Essa lista não precisa encolher.',
'A sabedoria que você acumulou é um recurso — não um arquivo morto.',
'Você tem tempo suficiente para o que realmente importa. Comece agora.',
'O próximo capítulo pode ser o mais rico de todos — se você o escrever com intenção.',
'Não é tarde para nada que ainda faz seu coração acelerar.',
'O que você plantou ao longo da vida vai continuar florescendo. Observe.',
'Você ainda tem conversas a ter, lugares a ver, pessoas a amar. Não feche nenhuma porta antes da hora.',
'O futuro que você imagina agora com clareza tem mais chance de acontecer do que pensa.',
'Há uma leveza em saber o que importa. Você sabe. Use isso.',
'O melhor presente que você pode dar ao seu futuro é a atenção que você dedica ao presente.'
],

/* ════════════════════════════════════════
   FIM — menos de 5.000 biscoitos
   ════════════════════════════════════════ */
fim: [
/* presença */
'Cada momento inteiramente vivido agora vale por muitos vividos pela metade.',
'Você chegou ao ponto em que presença não é prática — é prioridade.',
'O que está acontecendo ao seu redor agora mesmo é real e é suficiente.',
'Você já sabe que o tempo não volta. Então esta tarde, este momento, esta conversa — são tudo.',
'Não existe lugar melhor para estar do que completamente aqui.',
'A qualidade de cada momento agora importa mais do que a quantidade.',
'Estar plenamente presente é a coisa mais valiosa que você pode oferecer a si mesmo.',
'O que você vê quando para de pensar no passado e no futuro ao mesmo tempo? Veja isso.',
'Presença inteira é o mais puro luxo disponível.',
'Você viveu o suficiente para saber: o único tempo real é agora.',
'Este momento, exatamente como está, tem valor inteiro.',
'O que você ainda quer sentir completamente? Permita-se sentir.',
'Há uma beleza particular no agora que só quem chegou até aqui consegue ver.',
'Você tem toda razão de estar aqui, completamente.',
'Cada segundo que você está realmente presente é um segundo que você genuinamente viveu.',

/* gentileza consigo */
'Você merece uma gentileza consigo mesmo que não exige mais nenhuma justificativa.',
'Chegou a hora de tratar-se com a mesma ternura que você reservou para os outros por anos.',
'Você não precisa mais ganhar o direito de ser gentil consigo mesmo.',
'Tudo o que você carregou com dureza pode agora ser carregado com suavidade.',
'Você sobreviveu — e isso merece a mais profunda compaixão.',
'A voz crítica interna cumpriu seu papel. Agora pode descansar.',
'Você merece paz consigo mesmo. Não como conquista — como direito.',
'Cuide de si com toda a ternura que você sabe oferecer. Você sabe muito.',
'Não há nada que você precise provar para merecer gentileza agora.',
'A autocompaixão nesta fase é a forma mais inteligente de se amar.',
'Você pode olhar para si mesmo com os olhos que usaria para alguém que amou por toda a vida.',
'Gentileza consigo agora não é fraqueza. É maturidade completa.',
'O que você ainda se cobra que poderia simplesmente soltar?',
'Você fez o que pôde com o que tinha. Isso é suficiente.',
'Tratar-se bem agora é honrar tudo que você atravessou.',

/* coragem do cotidiano */
'A coragem que você acumulou ao longo da vida é sua. Ela não vai embora.',
'Ser honesto consigo mesmo sobre o que quer e o que precisa ainda exige bravura — e vale a pena.',
'Você ainda tem atos de coragem pela frente. E você tem o que precisa para eles.',
'Pedir o que você precisa quando precisa é coragem pura.',
'A bravura de continuar se importando com a vida é das mais silenciosas e das mais reais.',
'Você ainda vai tomar decisões difíceis. Você está preparado.',
'A coragem de mostrar quem você é sem pedir desculpa não tem prazo de validade.',
'Continuar crescendo em qualquer fase da vida é um ato de bravura.',
'Fazer escolhas que honram quem você é — isso é coragem no cotidiano.',
'Você tem a coragem de quem sobreviveu a muito. Use-a a favor do que ainda quer.',
'Dizer a verdade com amor ainda é o ato mais corajoso em qualquer conversa.',
'A bravura de ser vulnerável com quem você ama não diminui com o tempo.',
'Você não precisa mais provar sua coragem. Mas pode usá-la.',
'Cada dia em que você se levanta e escolhe o que importa é um ato de bravura.',
'A coragem de ser exatamente quem você é é a mais completa de todas.',

/* descanso sem culpa */
'Você merece descanso sem nenhuma justificativa. Ponto.',
'Não há nada que você precise fazer agora que não possa ser feito depois de descansar.',
'O ritmo que faz sentido para você agora é o ritmo certo. Não existe outro.',
'Você pode diminuir o passo sem diminuir quem você é.',
'Descanso agora é um ato de amor — por você e por quem está ao seu redor.',
'Você tem todo o direito de parar, ficar quieto, não fazer nada.',
'O que você ainda carrega por hábito que poderia soltar por escolha?',
'Silêncio e quietude são formas de sabedoria que você ganhou.',
'Você não deve produção ou performance a ninguém nesta fase.',
'O prazer de uma tarde sem pressa é um dos mais ricos que existem.',
'Descansar não é desistir. É honrar o que você ainda tem pela frente.',
'Você pode parar de correr. Chegou onde importa.',
'Não há medida externa de quanto você precisa fazer. Apenas a sua.',
'Pausa não é ausência de vida. É presença de um tipo diferente.',
'Descanso profundo é um presente que você pode se dar agora.',

/* autoconhecimento */
'Você se conhece melhor do que pensa. Confie nisso.',
'A sabedoria que você acumulou sobre si mesmo é um dos seus maiores bens.',
'Você sabe o que te faz bem, o que te faz mal, o que importa. Aja a partir disso.',
'Autoconhecimento real não precisa ser exibido. Ele se mostra em como você vive.',
'Você tem uma clareza sobre si mesmo que só vem com o tempo. Use-a.',
'As partes de você que você ainda não entende completamente merecem curiosidade, não cobrança.',
'Você aprendeu mais sobre si mesmo nos momentos difíceis do que em qualquer outro.',
'Sua intuição sobre você mesmo é afinada. Confie nela mais do que nas opiniões externas.',
'O que você ainda está descobrindo sobre si mesmo? Essa descoberta tem valor.',
'Você sabe quem você é. Isso é raro. Valorize.',
'As contradições que você ainda carrega não são defeitos — são a textura de uma vida real.',
'Autoconhecimento profundo é um presente para quem está ao seu redor.',
'Você não precisa mais se explicar para si mesmo. Você já sabe.',
'O quanto de si mesmo você ainda tem para descobrir? Provavelmente mais do que imagina.',
'Conhecer-se desta forma é uma das conquistas mais silenciosas e mais reais.',

/* o corpo e o tempo */
'Seu corpo chegou até aqui com você. Cuide-o com gratidão.',
'O tempo que você tem neste corpo é precioso. Use-o com consciência.',
'Seu corpo carrega toda a história que você viveu. Honre-o.',
'O que seu corpo precisa agora, ele precisa. Ouça.',
'Mover-se, respirar, descansar — são os atos de autocuidado mais fundamentais.',
'Há uma relação de confiança entre você e seu corpo que foi construída por anos.',
'O corpo que você tem hoje mereceu cada cuidado que você lhe deu.',
'Envelhecer com graciosidade é uma arte que você pode praticar.',
'Prazer físico não tem prazo de validade. Você ainda tem direito a ele.',
'O bem-estar físico que você cultiva agora é um presente para quem você ainda vai ser.',
'Seu corpo não é apenas a casa onde você vive — é quem você é, em parte.',
'O que seu corpo pede com mais frequência agora é o que ele mais precisa.',
'Cuidar do corpo é cuidar de tudo que veio com ele.',
'Há uma beleza no corpo que viveu muito. Você a tem.',
'Respeitar o ritmo do seu corpo agora é uma das formas mais profundas de se amar.',

/* alegria pequena */
'O que ainda te faz rir sem motivo é um dos maiores tesouros que você tem.',
'Alegria pequena, frequente e real é mais valiosa do que qualquer realização grandiosa.',
'Você sabe que as melhores coisas da vida foram simples. Continue atrás delas.',
'O que te dá prazer puro, sem utilidade, sem justificativa — isso merece espaço.',
'Permita-se alegria. Você não precisa mais ganhar esse direito.',
'Uma boa risada com quem você ama ainda é uma das experiências mais completas.',
'Há beleza disponível a você agora em todo lugar. Pare para vê-la.',
'O que faz seus olhos brilharem ainda? Faça mais disso.',
'Desfrutar plenamente do que está bem na sua vida é um ato de sabedoria.',
'Alegria não precisa de motivo grandioso. Ela cabe nesta manhã, neste café.',
'Você tem história suficiente para saber: os momentos mais felizes foram os mais simples.',
'Leveza cultivada é um presente para você e para todos ao seu redor.',
'O prazer de existir — simples assim — ainda está disponível para você.',
'Alegria compartilhada multiplica. Você tem com quem compartilhar?',
'O que ainda te encanta? Não solte isso.',

/* relacionamentos como espelho */
'As pessoas que você ama e que te amam são o legado mais real que existe.',
'Quem ainda está ao seu lado depois de tudo é parte do melhor que você construiu.',
'Você aprendeu que amor profundo não é perfeição — é permanência através das imperfeições.',
'As relações que você cultivou com cuidado são o que mais vai ficar.',
'Quem você ainda quer dizer o que não disse? Esse momento pode ser agora.',
'Amor que durou é um milagre cotidiano. Honre-o.',
'As pessoas que te conhecem de verdade são um tesouro inestimável.',
'Você aprendeu que presença real numa relação é mais rara e mais valiosa do que qualquer outra coisa.',
'O que você ainda quer construir com quem você ama? Há tempo.',
'As conversas mais importantes ainda podem acontecer. Não adie.',
'Quem te faz sentir completamente você mesmo merece saber disso.',
'O amor que você cultivou ao longo da vida é parte do que você deixa no mundo.',
'Estar verdadeiramente presente para alguém que você ama é o maior presente.',
'Relações profundas não se fazem em quantidade — se fazem em profundidade. Você tem isso.',
'O quanto de si mesmo você ainda quer mostrar para quem você ama?',

/* memória e identidade */
'Você chegou até aqui. Isso é, por si só, uma história extraordinária.',
'A pessoa que você se tornou foi construída por escolhas que exigiram tudo de você.',
'Sua história tem o valor de tudo que você sobreviveu e de tudo que você amou.',
'Você tem memórias que ninguém mais tem. Elas são únicas e preciosas.',
'O que permaneceu em você depois de tudo que passou é o núcleo mais verdadeiro do que você é.',
'Você não é o que aconteceu com você. É o que você fez com o que aconteceu.',
'Sua identidade é o resultado de cada vez que você escolheu continuar.',
'As pessoas que você influenciou ao longo da vida carregam parte de você.',
'Há dignidade profunda em tudo que você atravessou.',
'O que você preservou de si mesmo em meio a tudo é o que define quem você é.',
'Sua história merece ser contada — a você mesmo, antes de tudo.',
'Você tem uma continuidade que atravessa todas as fases da sua vida. Isso é caráter.',
'Quem você foi em cada fase tinha sabedoria própria. Todas merecem respeito.',
'A versão de você que chegou até aqui é a mais completa que já existiu.',
'Você é mais do que a soma dos seus anos — é a soma de tudo que escolheu ser.',

/* futuro como possibilidade */
'O que você ainda quer viver é tão válido quanto tudo que já viveu.',
'Não existe hora tardia para o que ainda faz sentido para você.',
'Você tem sabedoria suficiente para fazer os próximos capítulos os mais ricos de todos.',
'O futuro que ainda é seu pode ser exatamente o que você precisa que seja.',
'Há coisas que só quem chegou até aqui pode fazer e sentir. Você está aqui.',
'O que você ainda quer deixar no mundo? Essa resposta importa.',
'Você ainda vai se surpreender com o que é capaz de sentir e oferecer.',
'O próximo capítulo não precisa ser menor que os anteriores. Pode ser o mais profundo.',
'Você tem todo o direito de continuar sonhando — de uma forma ou de outra.',
'O que você ainda quer dizer, criar, construir, sentir? Há espaço para isso.',
'A sabedoria que você tem agora é o recurso mais valioso para o que vem.',
'Você viveu o suficiente para saber o que importa. Invista nisso.',
'O futuro de quem chegou até aqui ainda tem surpresas boas reservadas.',
'Há beleza no que ainda está por vir. Deixe-se ser surpreendido.',
'O melhor presente que você pode se dar é continuar aqui, completamente.'
],

/* ════════════════════════════════════════
   VENCIDO — biscoito expirado
   Frase única, gentil, sem julgamento.
   ════════════════════════════════════════ */
vencido: 'Este biscoito envelheceu esperando. O de amanhã vai te encontrar pronto.'

};
